### ISSUE TITLE
Segmentation violation

### ISSUE THREAD

**Issue by nullcult** [optiv/Freeze#11]
Hi. Am stuck in a loop with this error. 
Am running go version go1.19.8

![freeze](https://user-images.githubusercontent.com/63312212/235663156-e00bcefc-e1ab-4d0b-be9b-6b34cbe6e996.jpg)

**Comment by Tylous** [comment]
This looks to be an issue with Garble remove the .lib folder and try with an older version of go like 1.19.2

**Comment by qgrosperrin** [comment]
I have the same problem and tried every single version from 1.19.2 and it only builds starting with 1.19.9 for me otherwise I get the below 
```
└─$ go build Freeze.go
# syscall
/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1321:6: Setrlimit redeclared in this block
        /usr/local/go/src/syscall/rlimit.go:42:6: other declaration of Setrlimit
/usr/local/go/src/syscall/rlimit.go:38:3: undefined: setrlimit
/usr/local/go/src/syscall/rlimit.go:43:9: undefined: setrlimit
```

**Comment by qgrosperrin** [comment]
I have the same problem and this doesn't work for me with 1.19.2 (same error as above)

**Comment by qgrosperrin** [comment]
I have reverted to 1.20.4 and edited https://github.com/optiv/Freeze/blob/main/Utils/Utils.go#L41 to pull latest commit rather than latest release. 

The issue is known in garble https://github.com/burrowers/garble/issues/694, but was fixed in March and latest release is from February.

I also had to go get golang.org/x/sys/windows then, as `go build Freeze.go` was complaining this was missing once garble was fixed. It built successful after that

**Comment by nullcult** [comment]
@qgrosperrin Thanks for this. I only did a `git pull origin master` for gable and everything complied just perfect.
